export const purple = '#673ab7'
export const lighterPurple = '#9575cd'
export const blueGrey = '#607d8b'
export const darkBlueGrey = '#546e7a'
export const lightGrey = '#cfd8dc'
export const white = '#ffffff'