export const purple = '#673ab7'
export const lighterPurple = '#9575cd'
export const blueGrey = '#607d8b'
export const darkBlueGrey = '#546e7a'
export const lightGrey = '#cfd8dc'
export const green = '#8bc34a'
export const red = '#ff5722'
export const white = '#ffffff'